version: "3"
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zerox
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: zerox_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d/

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    depends_on:
      - db
    environment:
      PGRST_DB_URI: "postgres://zerox:${POSTGRES_PASSWORD}@db:5432/zerox_db"
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
